In [24]:
import torch

x=torch.ones(5)
y=torch.zeros(3)
w=torch.randn(5,3,requires_grad=True)
b=torch.randn(3,requires_grad=True)
z=torch.matmul(x,w)+b
loss=torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [25]:
loss

tensor(0.6355, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [26]:
print(f"Gradient function for z={z.grad_fn}")
print(f"Gradient function for loss={loss.grad_fn}")

Gradient function for z=<AddBackward0 object at 0x7f7dc26a9330>
Gradient function for loss=<BinaryCrossEntropyWithLogitsBackward0 object at 0x7f7dc26a92d0>


In [27]:
loss.backward()
print(f"Gradient of w is {w.grad}")
print(f"Gradient of b is {b.grad}")

Gradient of w is tensor([[0.0780, 0.2381, 0.1070],
        [0.0780, 0.2381, 0.1070],
        [0.0780, 0.2381, 0.1070],
        [0.0780, 0.2381, 0.1070],
        [0.0780, 0.2381, 0.1070]])
Gradient of b is tensor([0.0780, 0.2381, 0.1070])


In [28]:
z=torch.matmul(x,w)+b
print(z.requires_grad)
with torch.no_grad():
    z=torch.matmul(x,w)+b
print(z.requires_grad)

True
False


In [30]:
z=torch.matmul(x,w)+b
#detach for mark some parameters as frozen parameters
#speed up computations
z_det=z.detach()
print(z.requires_grad)
print(z_det.requires_grad)

True
False


In [77]:
inp=torch.eye(4,5,requires_grad=True)
out=(inp+1).pow(2).t()
print(f"inp :\n {inp}")
print(f"output : \n{out}")
print(f"torch one like is\n{torch.ones_like(out)}")
#backward: the first argument represent the scaling factor
out.backward(torch.ones_like(out),retain_graph=True)
print(f"First call\n {inp.grad}")
out.backward(torch.ones_like(out),retain_graph=True)
print(f"Second call\n {inp.grad}")
#because when doing backward propagation,torch will accumulates the gradients
inp.grad.zero_()
out.backward(torch.ones_like(out),retain_graph=True)
print(inp.grad)

inp :
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], requires_grad=True)
output : 
tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]], grad_fn=<TBackward0>)
torch one like is
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
First call
 tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
Second call
 tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
