In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets,transforms

In [2]:
device=("cuda")
print(device)

cuda


In [3]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [4]:
model=NeuralNetwork().to(device)
model

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [8]:
x=torch.rand(1,28,28,device=device)
logits=model(x)
print(f"Output of model is: {logits}")
pred_probab=nn.Softmax(dim=1)(logits)
print(f"Probability of output is: {pred_probab}")
pred=pred_probab.argmax(1)
print(f"Predicted class: {pred.item()}")

Output of model is: tensor([[-0.0636,  0.1183, -0.0008,  0.0389,  0.0498, -0.0687, -0.0993,  0.0164,
         -0.0739,  0.0416]], device='cuda:0', grad_fn=<AddmmBackward0>)
Probability of output is: tensor([[0.0940, 0.1128, 0.1001, 0.1042, 0.1053, 0.0935, 0.0907, 0.1018, 0.0931,
         0.1044]], device='cuda:0', grad_fn=<SoftmaxBackward0>)
Predicted class: 1


In [9]:
# m=nn.Softmax(dim=1)
# input1=torch.randn(2,3)
# print(input1)
# print(m(input1))

tensor([[ 1.7148,  1.2693,  0.3414],
        [-0.7822,  0.8762, -0.6213]])
tensor([[0.5281, 0.3382, 0.1337],
        [0.1347, 0.7072, 0.1582]])


In [12]:
input_image=torch.rand(3,28,28)
# Flatten
#We initialize the nn.Flatten layer to convert each 2D 28x28 image into a contiguous array of 784 pixel values
flatten=nn.Flatten()
flat_image=flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [13]:
#The linear layer is a module that applies a linear transformation on the input using its stored weights and biases.
layer1=nn.Linear(in_features=28*28,out_features=20)
hidden1=layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [14]:
'''
Non-linear activations are what create the complex mappings between the model’s inputs and outputs.
They are applied after linear transformations to introduce nonlinearity, 
helping neural networks learn a wide variety of phenomena
'''
print(f"Before ReLU: {hidden1}")
hidden1=nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[ 0.2097,  0.1393,  0.7525,  0.4721, -0.4186,  0.2671,  0.4827, -0.4227,
         -0.0658, -0.5404,  0.2956, -0.6622, -0.4143,  0.0202,  0.2811,  0.6991,
          0.2598,  0.4161,  0.0369, -0.0701],
        [-0.0184,  0.1485,  0.1975,  0.3544, -0.3395,  0.2417,  0.1811, -0.0210,
         -0.0544, -0.2313, -0.1825, -0.2954, -0.4157, -0.0251,  0.1087,  0.6022,
         -0.1316,  0.2593, -0.2174,  0.2928],
        [-0.0825,  0.0788,  0.7966,  0.7166, -0.3710, -0.0398,  0.3695, -0.2818,
         -0.1118, -0.3037,  0.0022, -0.9169, -0.0216,  0.3939,  0.0483,  0.1586,
         -0.0533,  0.4616, -0.2868,  0.1881]], grad_fn=<AddmmBackward0>)
After ReLU: tensor([[0.2097, 0.1393, 0.7525, 0.4721, 0.0000, 0.2671, 0.4827, 0.0000, 0.0000,
         0.0000, 0.2956, 0.0000, 0.0000, 0.0202, 0.2811, 0.6991, 0.2598, 0.4161,
         0.0369, 0.0000],
        [0.0000, 0.1485, 0.1975, 0.3544, 0.0000, 0.2417, 0.1811, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1087

In [19]:
seq_modules=nn.Sequential(
     flatten,
     layer1,
     nn.ReLU(),
     nn.Linear(20,10)
)
input_image=torch.rand(3,28,28)
logits=seq_modules(input_image)
logits

tensor([[ 1.1187e-01, -4.3746e-02,  2.9669e-02, -2.8039e-02,  7.5639e-02,
         -1.5472e-01,  2.2069e-04,  4.4456e-02,  8.7867e-02, -3.4805e-01],
        [ 1.7630e-01, -3.3110e-02, -4.4534e-03,  2.9763e-02,  1.2371e-01,
         -1.3249e-01, -3.1712e-02,  3.7302e-02,  7.4706e-02, -4.3073e-01],
        [ 7.2892e-02, -2.1234e-01, -4.1789e-03, -5.0202e-03,  1.2049e-01,
         -1.0709e-01, -5.9611e-02,  1.5952e-01,  8.1887e-02, -4.6853e-01]],
       grad_fn=<AddmmBackward0>)

In [18]:
softmax=nn.Softmax(dim=1)
pred_probab=softmax(logits)
pred_probab

tensor([[0.1151, 0.1260, 0.0742, 0.0861, 0.0811, 0.0802, 0.1165, 0.1068, 0.1089,
         0.1050],
        [0.1324, 0.1294, 0.0761, 0.0966, 0.0711, 0.0809, 0.0940, 0.1267, 0.1045,
         0.0883],
        [0.1180, 0.1348, 0.0680, 0.0995, 0.0762, 0.0802, 0.1081, 0.1135, 0.1136,
         0.0882]], grad_fn=<SoftmaxBackward0>)

In [20]:
pred_probab.argmax(1)

tensor([1, 0, 1])

In [21]:
print(f"Model structure: {model}\n")
for name,param in model.named_parameters():
    print(f"Layer: {name}| Size: {param.size()}| Values: {param[:2]}\n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

Layer: linear_relu_stack.0.weight| Size: torch.Size([512, 784])| Values: tensor([[ 0.0146, -0.0249,  0.0315,  ..., -0.0195, -0.0096, -0.0006],
        [ 0.0005, -0.0346,  0.0045,  ..., -0.0061, -0.0315, -0.0064]],
       device='cuda:0', grad_fn=<SliceBackward0>)

Layer: linear_relu_stack.0.bias| Size: torch.Size([512])| Values: tensor([0.0070, 0.0059], device='cuda:0', grad_fn=<SliceBackward0>)

Layer: linear_relu_stack.2.weight| Size: torch.Size([512, 512])| Values: tensor([[-0.0247,  0.0055,  0.0085,  ..., -0.0036,  0.0368,  0.0168],
        [-0.0417, -0.0036,  0.0214,  ..., -0.0261,  0.0283,  0.0252]],
       device='cuda:0', grad_fn=<SliceBackward0>)