In [1]:
import torch
import numpy as np

In [ ]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_data.size()

torch.Size([2, 2])

In [ ]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)

In [ ]:
print(type(np_array))
print(type(x_np))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [ ]:
x_ones=torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones}\n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])



In [ ]:
x_rand=torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor: \n {x_rand}\n")

Random Tensor: 
 tensor([[0.0442, 0.4840],
        [0.4573, 0.0440]])



In [ ]:
shape=(2,3)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zero_tensor=torch.zeros(shape)
print(f"Random Tensor:\n{rand_tensor}\n")
print(f"Ones Tensor:\n{ones_tensor}\n")
print(f"Zero Tensor:\n{zero_tensor}\n")

Random Tensor:
tensor([[0.1037, 0.3743, 0.1332],
        [0.3124, 0.4307, 0.8837]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zero Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [ ]:
tensor=torch.rand(3,4)
print(f"datatype of tensor {tensor.dtype}")
print(f"device tensor is stored on: {tensor.device}")
tensor=tensor.cuda()
print(f"device tensor is stored on: {tensor.device}")

datatype of tensor torch.float32
device tensor is stored on: cpu
device tensor is stored on: cuda:0


In [ ]:
tensor=torch.ones(4,4)
print(f"First row is : {tensor[0]}")
print(f"First colum is : {tensor[:,0]}")
print(f"Last colum is : {tensor[:,-1]}")
tensor[:,-1]=0
print(tensor)


First row is : tensor([1., 1., 1., 1.])
First colum is : tensor([1., 1., 1., 1.])
Last colum is : tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


In [ ]:
t1=torch.cat([tensor,tensor,tensor],dim=1)
print(t1)
print(t1.size())

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])
torch.Size([4, 12])


In [ ]:
t2=torch.stack([tensor,tensor,tensor],dim=1)
print(f"Original tensor size :{tensor.size()}")
print(f"tensor stack in 1 dimension: {t2.size()}")
t2=torch.stack([tensor,tensor,tensor],dim=0)
# usually use this to stack the training data
print(f"tensor stack in 0 dimension: {t2.size()}")

Original tensor size :torch.Size([4, 4])
tensor stack in 1 dimension: torch.Size([4, 3, 4])
tensor stack in 0 dimension: torch.Size([3, 4, 4])


In [ ]:
y1=tensor@tensor.T
y2=tensor.matmul(tensor.T)
y3=torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out=y3)
print(y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [ ]:
z1=tensor*tensor
z2=tensor.mul(tensor)
z3=torch.rand_like(z1)
torch.mul(tensor,tensor.T,out=z3)
print(z3)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [0., 0., 0., 0.]])


In [ ]:
agg=tensor.sum()
print(agg)
agg.item()

tensor(12.)


12.0

In [ ]:
#using the _ to operation the tensor in-place
print(f"{tensor}\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

tensor([[6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.]])
